- hosts: localhost
  vars:
    thruk_path: /etc/thruk
    thruk_share_dir: /usr/share/thruk
    nagios_path: /etc/nagios3
    nagios_bin: /usr/share/nagios
    nagios_share_dir: /usr/share/nagios
    apache_user: www-data

  tasks:
    - name: Add Consol Labs GPG key
      apt_key:
        url: https://labs.consol.de/repo/stable/RPM-GPG-KEY

    - name: Add Consol Labs repository
      apt_repository:
        repo: "deb http://labs.consol.de/repo/stable/ubuntu {{ ansible_distribution_release }} main"

    - name: Remove Consol Labs repository
      apt_repository:
        repo: "deb http://labs.consol.de/repo/stable/ubuntu {{ ansible_distribution_release }} main"
        state: absent
      tags: never, uninstall

    - name: Install Thruk
      apt:
        name: thruk
        state: latest

    - name: Uninstall Thruk
      apt:
        name: thruk
        state: absent
      tags: never, uninstall

    - name: Get package facts
      package_facts:
        manager: auto

    - name: Set Thruk application version
      command: application-version-set "{{ ansible_facts.packages['thruk'][0]['version'] }}"

    - name: Symlink logos from Nagios
      file:
        src: "{{ nagios_share_dir }}/htdocs/images/logos/base"
        dest: "{{ thruk_share_dir }}/themes/themes-available/Thruk2/images/logos/base"
        state: link

    - name: Template default index.html
      template:
        src: templates/index.html
        dest: "/var/www/html/index.html"

    - name: Template Nagios backend
      template:
        src: templates/nagios_backend.conf.j2
        dest: "{{ thruk_path }}/thruk_local.d/nagios_backend.conf"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
      notify: restart thruk
      tags: config

    - name: Template charm config
      template:
        src: templates/charm_config.conf.j2
        dest: "{{ thruk_path }}/thruk_local.d/charm_config.conf"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
      notify: restart thruk
      tags: config

  handlers:
    - name: restart thruk
      service:
        name: thruk
        state: restarted
